import firebaseConfig from "../../firebase-applet-config.json";

export interface DriveExportResult {
  success: boolean;
  fileId?: string;
  fileUrl?: string;
  error?: string;
}

// Request Google Drive OAuth Token via Google Identity Services
export function requestGoogleDriveToken(): Promise<string> {
  return new Promise((resolve, reject) => {
    if (typeof window === "undefined") {
      reject(new Error("Window not defined"));
      return;
    }

    // Load GIS script if not present
    if (!window.google?.accounts?.oauth2) {
      const script = document.createElement("script");
      script.src = "https://accounts.google.com/gsi/client";
      script.onload = () => {
        initTokenClient(resolve, reject);
      };
      script.onerror = () => reject(new Error("Failed to load Google GIS client library"));
      document.body.appendChild(script);
    } else {
      initTokenClient(resolve, reject);
    }
  });
}

function initTokenClient(resolve: (token: string) => void, reject: (reason: any) => void) {
  try {
    const client = window.google.accounts.oauth2.initTokenClient({
      client_id: firebaseConfig.oAuthClientId,
      scope: "https://www.googleapis.com/auth/drive.file",
      callback: (response: any) => {
        if (response.error) {
          reject(new Error(response.error_description || response.error));
          return;
        }
        if (response.access_token) {
          resolve(response.access_token);
        } else {
          reject(new Error("No access token returned from Google"));
        }
      },
    });
    client.requestAccessToken();
  } catch (err) {
    reject(err);
  }
}

// Upload file content (e.g. CSV or JSON) directly to Google Drive API
export async function uploadFileToDrive(
  token: string,
  fileName: string,
  content: string,
  mimeType: string = "text/csv"
): Promise<DriveExportResult> {
  try {
    const metadata = {
      name: fileName,
      mimeType: mimeType,
      description: "Generated by Inco Inventory Counter Web App",
    };

    const form = new FormData();
    form.append(
      "metadata",
      new Blob([JSON.stringify(metadata)], { type: "application/json" })
    );
    form.append("file", new Blob([content], { type: mimeType }));

    const res = await fetch("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink,webContentLink", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
      },
      body: form,
    });

    if (!res.ok) {
      const errText = await res.text();
      throw new Error(`Google Drive API error (${res.status}): ${errText}`);
    }

    const data = await res.json();
    return {
      success: true,
      fileId: data.id,
      fileUrl: data.webViewLink || `https://drive.google.com/file/d/${data.id}/view`,
    };
  } catch (err: any) {
    console.error("Google Drive upload error:", err);
    return {
      success: false,
      error: err.message || "Upload failed",
    };
  }
}

// Global declaration for window.google
declare global {
  interface Window {
    google: any;
  }
}
